TRPO-Lab5.Web/Models/ErrorViewModel.cs
using System;

namespace TRPO_Lab5.Web.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

TRPO-Lab5.Web/Models/FormulesViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace TRPO_Lab5.Web.Models
{
    public class FormulesViewModel
    {
        public double A{ get; set; }

        public double B{ get; set; }
         
        public double C{ get; set; }

        public double P{ get; set; }

        public double Square { get; set; }
    }
}

TRPO-Lab5.Web/Controllers/FormulesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;
using static TRPO_Lab5.Web.Models.FormulesViewModel;
using static TRPO_Lab3.Lib.Formules;


namespace TRPO_Lab5.Web.Controllers
{
    public class FormulesController : Controller
    {
        [HttpGet]
        public ActionResult TreyGSq()
        {
            return View();
        }

        [HttpPost]
        public ActionResult TreyGSq(string a, string b, string c, string s)
        {
            double square = TreyG(Convert.ToDouble(a), Convert.ToDouble(b), Convert.ToDouble(c), Convert.ToDouble(s));
            ViewBag.Result = Math.Round(square, 3);
            return View();
        }

    }
}

TRPO-Lab5.Web/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using TRPO_Lab5.Web.Models;

namespace TRPO_Lab5.Web.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

TRPO-Lab5.Web/Views/Formules/TreyGSq.cshtml
@{
    IgnoreBody();
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>TRPO_Lab5.Web</title>
    <link rel="stylesheet" href="~/css/calc.css" />
</head>
<body>
    <main>
        <h1 class="main__header">Расчёт площади треугольника по формуле Герона</h1>
        <img class="main_TreyG" src="~/img/645b757413410d67ef227a65a8dd118a.jpg" alt="TreyG" />
        <form class="main__form" action="" method="post">
            <div>
                <span class="form__unvalid">Необходимо вводить только положительные значения</span>
                <input class="form__input" type="number" name="a" placeholder="Сторона треугольника а" />
                <input class="form__input" type="number" name="b" placeholder="Сторона треугольника b" />
                <input class="form__input" type="number" name="с" placeholder="Сторона треугольника c" />
                <input class="form__input" type="number" name="s" placeholder="Полупериметр s" />
                <button class="form__btn" asp-area="" asp-controller="Formules" asp-action="TreyGSq">Рассчитать</button>
                <p class="form__result">Результат: @ViewBag.Result</p>
            </div>
        </form>
    </main>
    <script src="~/js/site.js" asp-append-version="true"></script>
</body>
</html>

TRPO-Lab5.Web/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

TRPO-Lab5.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - TRPO_Lab5.Web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">TRPO_Lab5.Web</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - TRPO_Lab5.Web - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>